### ISSUE TITLE
Error when launching xanaxbetter

### ISSUE THREAD

**Issue by chuckynorris616** [rguedes/xanaxbetter#22]
Logging in to https://apollo.rip...
Traceback (most recent call last):
  File "./xanaxbetter", line 235, in <module>
    main()
  File "./xanaxbetter", line 119, in main
    api = xanaxapi.XanaxAPI(username, password)
  File "/Users/system-void/xanaxbetter-master/xanaxapi.py", line 84, in __init__
    self._login()
  File "/Users/system-void/xanaxbetter-master/xanaxapi.py", line 91, in _login
    r = self.session.post(loginpage, data=data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)

**Comment by iBL1nK** [comment]
See: https://apollo.rip/forums.php?action=viewthread&threadid=985&postid=30105#post30105

> It's because we're no longer allowing http connections to the site (they're all https) that you're just now experiencing this issue. The problem here is that Ubuntu and macOS ship with an older version of python (for you in this case 2.7.6) that has issues with its openssl.
If you're on Ubuntu (or Bash on Ubuntu on Windows or whatever), then you can do:
sudo apt-get remove python-pip
sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get install python2.7
python --version
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip --version

-- itismadness

**Comment by chuckynorris616** [comment]
How do i fix on OSX?

**Comment by iBL1nK** [comment]
I don't have any experience with OSX, sorry, but i would guess either figure out where to get older versions of pip and python for OSX, or just use linux emulator or install linux

**Comment by taylorthurlow** [comment]
Should be able to do `brew install python` on OSX if you have Homebrew installed.

**Comment by itismadness** [comment]
Yes, the instructions for updating python for Ubuntu are:
```
sudo apt-get remove python-pip
sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get install python2.7
python --version
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip --version
```

and for mac:
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install python
```
(only run the first line if you don't have homebrew installed)
