### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by XelionXS** [rguedes/xanaxbetter#23]
When i try to execute Xanaxbetter :

`Traceback (most recent call last):
  File "./xanaxbetter", line 235, in <module>
    main()
  File "./xanaxbetter", line 119, in main
    api = xanaxapi.XanaxAPI(username, password)
  File "/home/xelion/xanaxbetter/xanaxapi.py", line 84, in __init__
    self._login()
  File "/home/xelion/xanaxbetter/xanaxapi.py", line 94, in _login
    accountinfo = self.request('index')
  File "/home/xelion/xanaxbetter/xanaxapi.py", line 120, in request
    raise RequestException
xanaxapi.RequestException`

**Comment by itismadness** [comment]
This happens when the request for a page fails on the site for whatever reason. I plan to improve the error message on the exception to indicate this, but the solution is wait until you're confident the site is working again and try again.

**Comment by Cramstyler** [comment]
I get exactly the same error, even though it appears that the site is up and running perfectly. Has there been any solution?
