### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by Mes291** [rguedes/xanaxbetter#34]
When i try to execute Xanaxbetter :
Simply cannot login.
Traceback (most recent call last): File "./xanaxbetter", line 235, in <module> main() File "./xanaxbetter", line 119, in main api = xanaxapi.XanaxAPI(username, password) File "/home/xelion/xanaxbetter/xanaxapi.py", line 84, in __init__ self._login() File "/home/xelion/xanaxbetter/xanaxapi.py", line 94, in _login accountinfo = self.request('index') File "/home/xelion/xanaxbetter/xanaxapi.py", line 120, in request raise RequestException xanaxapi.RequestException

**Comment by rubdos** [comment]
Same since today. Updating dependencies helped:

    pip install --user -r requirements.txt

**Comment by rubdos** [comment]
Mmm, no, I have it again.

**Comment by rubdos** [comment]
```
Logging in to https://apollo.rip...
Traceback (most recent call last):
  File "/home/****/.local/bin/xanaxbetter", line 4, in <module>
    __import__('pkg_resources').run_script('xanaxbetter==1.4', 'xanaxbetter')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/****/.local/lib/python2.7/site-packages/xanaxbetter-1.4-py2.7.egg/EGG-INFO/scripts/xanaxbetter", line 235, in <module>
    
  File "/home/****/.local/lib/python2.7/site-packages/xanaxbetter-1.4-py2.7.egg/EGG-INFO/scripts/xanaxbetter", line 119, in main
    
  File "build/bdist.linux-aarch64/egg/xanaxapi.py", line 84, in __init__
  File "build/bdist.linux-aarch64/egg/xanaxapi.py", line 94, in _login
  File "build/bdist.linux-aarch64/egg/xanaxapi.py", line 120, in request
xanaxapi.RequestException

```

**Comment by rubdos** [comment]
Looks like the `ajax.php` request returns empty. Serversided problem? Or did the "protocol" change?

**Comment by rubdos** [comment]
Looks like server sided, because most of the time it randomly works.
